[package]
name = "reservoir-protocol"
version = "0.1.0"
authors = [ "Ruan Pearce-Authers <ruan@reservoirdb.com>" ]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
uuid = { version = "0.8", features = [ "serde", "v4" ] }
bitflags = "1.2"
